### ISSUE TITLE
손절 익절 타이밍

### ISSUE THREAD

**Issue by kwondam** [oeritas/crypto-trading-bot#1]
횡보장이나 상승장이면 문제 없는데, 계속해서 하락하는 하락장이면 DOWN COUNT가 계속 높아서(UP이 간간히 높아져도 DOWN이 100 이렇게 되면 UP&DOWN이 동시에 7 이상일 때 -5 해주는게 쓸모 X), 손해가 클 것 같습니다. 즉, SELL CONDITION CHECK에서 손절하는 경우에 대한 처리가 없는것 같습니다. 있으면 언급 부탁드립니다.

**Comment by oeritas** [comment]
하락장인 경우는 고려했으나 코드에 넣진않았어. 차피 그건 머신러닝으로 돌려도 예측 못하고 크롤링으로 대응해도 예측을 빗나가니까. 그래서 하락장에 대한 대응으로 타이밍고려하는것보다 시장여러개 포트폴리오로 돌리는게 좋다고 생각하는데 아직 실험은 안해봤어
