### ISSUE TITLE
DOWN과 UP 카운트 기준

### ISSUE THREAD

**Issue by kwondam** [oeritas/crypto-trading-bot#2]
8, 7, 10 등등 여러 가지로 잡았는데, 기준이 뭔지 피드백 부탁드립니다.

**Comment by oeritas** [comment]
원래는 트렌드 읽어서 반영해보고, 너처럼 퍼센트로도 해봤는데 다 핵심적으로 맞아들어가지가 않아서 차라리 downcnt 하고 upcnt 를 동시에 돌려버려서 트렌드를 변수가 가지고 있게 했어. 그랬더니 얼추 맞더라고. 이전 이슈에서 말한 대하락장 대상승장은 안되지만 말이야. 애초에 이게 단타를 위한거라서 그런 장은 고려를 안한것도 있어. 그래서 만약 지금 하락장 물려버리면 답없지뭐.
그 숫자들의 기준은 그동안의 시장 등락폭 평균? 정도가 되겠네

**Comment by kwondam** [comment]
일단위 퍼센트로는 아예 없네. 홀딩하고 있기보다 나은건 많이 찾았는데, 원금보다 이익나는 경우는 아예 못찾았어. 더 작은 시간 단위에서는 몰라도, 자주 트레이딩 안할거면 명신 너가 한 카운트 방식이 나을듯.

**Comment by oeritas** [comment]
sell을 하게되면 test sell 을 거쳐서
무조건 원금보단 이익이 나는 구조긴한데 (그래서 저번일주일은 트레이드가 
문제는 시간하고 하락장이야.

시간문제는,
downcnt가 높아져서 buy했어 근데 더내려가서 올라올 기미가 안보여
근데 안팔고 기다리기만 하면 이득은 볼수있어
여기에 내 가정은 암호화폐시장이라도 결국엔 자본과 물리니까
자본에 인플레이션은 무조건 일어나니까 암호화폐 유입자본도 반드시 인플레의 영향을 받으니까
암호화폐 가격은 언젠간 오른다 라는 가정

하락장문제는,
이게 생각에 생각을 거듭해도 뚜렷한 기술적 해결책이 안 떠오르는데,
현재로선 하락장일때 downcnt가 이상치범위를 넘어서면 손절하고 sell한후
krw를 현재 대하락장이 아닌 적당한 하락장의 시장에 넣어서 buy 하는거야
대하락장시장보단 금방오를거니까 라는 가정으로.
근데 이런식으로 멀티마켓돌려도 리스크가 큰건 마찬가지지. 그래서 계속 생각중이야.
구미가 당긴다면 같이 기술적 해결책을 찾아보자
