### ISSUE TITLE
up_cnt랑 down_cnt 둘다 7 넘는 때가 어떨 때에요?

### ISSUE THREAD

**Issue by teberr** [oeritas/crypto-trading-bot#3]
그리고 요청하는 주기가 어떻게 되나요?

**Comment by oeritas** [comment]
첫번째,
예를 들어 1,0  -> 2,0 -> 1,1 이런식으로 되자나 
근데 하나가 0이면 하나만 계속올라가 3,0 -> 4,0 이렇게 
그럼 둘의 sum 이 커져
13,0 에서 부터 12,1 -> 11,2 -> 10,3 -> 9,4 -> 8,5 -> 7,6 이런식으로 되겠지
그럼 7,6 인게 업치락 뒤치락 했다는 걸 반영할순 있지만,
단타에서 필요한 트렌딩으론 과하거든
1,0 하고 거의 다를 바가 없게되는거지.
두번째,
요청하는주기 라고 한다면, request를 뿌리는걸 말하는거지?
그게 600ms 였나 700ms 였나 그럴텐데 그게 1초보단 좀 짧아
그건 리플시장에 맞춰져있다고 보면되는데 
커스텀하거나 데이터 쌓아보고 최적화시키거나 하면돼
